using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DNSServer.Modules.Fortinet
{
    enum FortinetCategory
    {
        DrugAbuse = 1,
        Hacking = 2,
        IllegalOrUnethical = 3,
        Discrimination = 4,
        ExplicitViolence = 5,
        ExtremistGroups = 6,
        ProxyAvoidance = 7,
        Plagiarism = 8,
        ChildAbuse = 9,
        AlternativeBeliefs = 10,
        Abortion = 11,
        OtherAdultMaterials = 12,
        AdvocacyOrganizations = 13,
        Gambling = 14,
        NudityAndRisque = 15,
        Pornography = 16,
        Dating = 17,
        WeaponsSales = 18,
        Marijuana = 19,
        SexEducation = 20,
        Alcohol = 21,
        Tobacco = 22,
        LingerieAndSwimsuit = 23,
        SportsHuntingAndWarGames = 24,
        FreewareAndSoftwareDownloads = 25,
        FileSharingAndStorage = 26,
        StreamingMediaAndDownload = 27,
        PeerToPeerFileSharing = 28,
        InternetRadioAndTV = 29,
        InternetTelephony = 30,
        MaliciousWebsites = 31,
        Phishing = 32,
        SpamURLs = 33,
        DynamicDNS = 34,
        NewlyObservedDomain = 35,
        NewlyRegisteredDomain = 36,
        Advertising = 37,
        BrokerageAndTrading = 38,
        Games = 39,
        WebBasedEmail = 40,
        Entertainment = 41,
        ArtsAndCulture = 42,
        Education = 43,
        HealthAndWellness = 44,
        JobSearch = 45,
        Medicine = 46,
        NewsAndMedia = 47,
        SocialNetworking = 48,
        PoliticalOrganizations = 49,
        Reference = 50,
        GlobalReligion = 51,
        Shopping = 52,
        SocietyAndLifestyles = 53,
        Sports = 54,
        Travel = 55,
        PersonalVehicles = 56,
        DynamicContent = 57,
        MeaninglessContent = 58,
        Folklore = 59,
        WebChat = 60,
        InstantMessaging = 61,
        NewsgroupsAndMessageBoards = 62,
        DigitalPostcards = 63,
        ChildEducation = 64,
        RealEstate = 65,
        RestaurantAndDining = 66,
        PersonalWebsitesAndBlogs = 67,
        ContentServers = 68,
        DomainParking = 69,
        PersonalPrivacy = 70,
        Auction = 71,
        FinanceAndBanking = 72,
        SearchEnginesAndPortals = 73,
        GeneralOrganizations = 74,
        Business = 75,
        InformationAndComputerSecurity = 76,
        GovernmentAndLegalOrganizations = 77,
        InformationTechnology = 78,
        ArmedForces = 79,
        WebHosting = 80,
        SecureWebsites = 81,
        WebBasedApplications = 82,
        CharitableOrganizations = 83,
        RemoteAccess = 84,
        WebAnalytics = 85,
        OnlineMeeting = 86
    }
}
